<button type="button" class="close" aria-hidden="true">&times;</button>
<div id="infoTitle" class="richmond-park">Richmond Park</div>
<div id="infoSubTitle">Adrian, 45</div>
<dix id="top">
	<img height="300px" width="600px" src="img/richmond_park/rich_park1.jpg">
</dix>
<div id="middleLeft"><img height="228px" width="299px" src="img/richmond_park/rich_park1_thumb.jpg"></div>
<div id="middleRight"><img height="228px" width="300px" src="img/richmond_park/rich_park2_thumb.jpg"></div>
<div id="bottomLeft"><img height="228px" width="299px" src="img/richmond_park/rich_park3_thumb.jpg"></div>
<div id="bottomRight"><img height="228px" width="300px" src="img/richmond_park/rich_park4_thumb.jpg"></div>
<div id="text"><p>"I’ve lived in London all of my life and have been fortunate enough to visit many places and really get to know this wonderful city I call home. London's history still astounds me and even after 45 years I still find new things and places to visit that amaze me. Being a keen gardner and a love for all things outdoors, the one place I find peace tranquility and instant gratification is Richmond Park. Numerous plants and smells adorn the carefully tended plantations and is a real treat for us gardeners. It's vast land is home to thousands of species of birds land and water, and over 600 fallow deer roam freely to enjoy lush grounds without fear.</p><p>Apart from the wildlife, Richmond Park is is steeped in history making it a significant part of London. It has a Grade 1 heritage listing and was once owned by Charles 1st way back in 1634. Many films have been made there because of it's idilic settings, grand lodges and numerous ponds. In my opinion it's a significant place to visit because it's an opportunity to embark on adventure, history, wildlife and interact in what I reckon is London's finest Royal Park.</p><p>Being a dog lover and owning two Boxers,it's the one place they truly come alive. Although Richmond Park is 3/4 miles away from where I live, it's the one place I visit on a weekly basis come rain or shine as it's a haven for dog walkers. They can roam happily and enjoy the smells and residue the wildlife leaves them to enjoy. They can swim, graze or on a hot day simply chill under the foliage of one of the huge trees that make up this wonderful place. It really is doggy heaven.</p><p>About 15 years ago, a close  friend decided to get married and found his dream venue situated inside the park called White Lodge. It's a former home to Royalty, now a ballet school and used in the film Billy Elliot. The walls are adorned with historical figures and artifacts. It's large and grand and simply takes your breath away. To have 100 friends and family enjoy the sunshine and enjoy the beautiful  manicured lawns dance the night away to celebrate a wedding was a memory that will stay with me forever.</p><p>Each time I visit Richmond Park and walk past the lodge, fond memories come back and I'm often temporarily transported. For that day, because you were surrounded by family and friends, you were able to create your atmosphere and create a memory that'll last long in the memory. It was kind  of the start of my love affair with the park as from that day on, I knew there was a lot more to see and there was simply no rush.”</p></div>