<button type="button" class="close" aria-hidden="true">&times;</button>
<div id="infoTitle" class="sounds">sounds of the universe, soho</div>
<div id="infoSubTitle">Jan, 48</div>
<dix id="top">
    <img height="300px" width="600px" src="img/sounds/sound1.jpg">
</dix>
<div id="middleLeft"><img height="228px" width="299px" src="img/sounds/sound1_thumb.jpg"></div>
<div id="middleRight"><img height="228px" width="300px" src="img/sounds/sound2_thumb.jpg"></div>
<div id="bottomLeft"><img height="228px" width="299px" src="img/sounds/sound3_thumb.jpg"></div>
<div id="bottomRight"><img height="228px" width="300px" src="img/sounds/sound4_thumb.jpg"></div>
<div id="text"><p>"Firstly,it is one of only a handful left in the Capital,in an area of soho that used to have a lot. I love music,and it also happens to be what I do for a living,I'm a musician,producer and songwriter.A big part of my job relies upon me understanding the way music is made on a deep level,this comes through studying it through listening.When I first became interested in music as a child in the 1970's there was no Internet and the only way to buy something you heard on the radio or on TV was from a shop,you couldn't listen online or download so you had to go to a shop. As I got more and more into music and started spending most of my money on it I really also enjoyed the time I was spending in the shops ,the community and atmosphere etc and this became a big part of it all for me. Whenever I'm in soho and have a little time to spare,I'll pop in to the shop to see what they have,soak up some of the atmosphere and get lost in music for a minute.</p><p>The atmosphere in the shop is special,they'll always be something playing with the vinyl or cd on display to show you what it is,people will be walking around flicking through the racks divided up into styles,Classic soul,new soul,house music,reggae,jazz,electronic ,Latin etc etc.New releases will be on display at a listening station with headphones ,related books ,magazines or club flyers  are on display..downstairs they'll be rare vinyl on display to buy or just look at or listen to.There will always be a conversation going on. As someone who's been buying music since my childhood and as a collector since my teens,I've  spent many hours blissfully lost in these temples to musical escapism and I still enjoy it as much now as ever,and although I buy and listen to just as much music online,I still enjoy the original special atmosphere to that particular type of social club that is the record shop,and this one is one of my favourites."</p></div>